const Menu = [
    {
        id: 1,
        image: "../images/Burger.jpg",
        name: "maggi",
        category: "breakfast",
        price: 25,
        description: "This is a tag that i am giving into this container because i have to create a content for this container.I would like to write to the point goodluck.",
    },
    {
        id: 1,
        image: "../images/sandwhich.webp",
        name: "Sandwich",
        category: "lunch",
        price: 25,
        description: "This is a tag that i am giving into this container because i have to create a content for this container.I would like to write to the point goodluck.",
    },
    {
        id: 1,
        image: "../images/Burger.jpg",
        name: "Burger",
        category: "breakfast",
        price: 25,
        description: "This is a tag that i am giving into this container because i have to create a content for this container.I would like to write to the point goodluck.",
    },
    {
        id: 1,
        image: "../images/sandwhich.webp",
        name: "Sandwich",
        category: "evening",
        price: 25,
        description: "This is a tag that i am giving into this container because i have to create a content for this container.I would like to write to the point goodluck.",
    },
    {
        id: 1,
        image: "../images/Burger.jpg",
        name: "Burger",
        category: "dinner",
        price: 25,
        description: "This is a tag that i am giving into this container because i have to create a content for this container.I would like to write to the point goodluck.",
    },
    {
        id: 1,
        image: "../images/Burger.jpg",
        name: "Burger",
        category: "breakfast",
        price: 25,
        description: "This is a tag that i am giving into this container because i have to create a content for this container.I would like to write to the point goodluck.",
    },
    {
        id: 1,
        image: "../images/sandwhich.webp",
        name: "Burger",
        category: "lunch",
        price: 25,
        description: "This is a tag that i am giving into this container because i have to create a content for this container.I would like to write to the point goodluck.",
    },
    {
        id: 1,
        image: "../images/sandwhich.webp",
        name: "Ankit",
        category: "ankit",
        price: 25,
        description: "This is a tag that i am giving into this container because i have to create a content for this container.I would like to write to the point goodluck.",
    },
    {
        id: 1,
        image: "../images/sandwhich.webp",
        name: "Latest Item",
        category: "New Item",
        price: 250,
        description: "This is a tag that i am giving into this container because i have to create a content for this container.I would like to write to the point goodluck.",
    }
];

export default Menu;  